### ISSUE TITLE
By default tab press issue

### ISSUE THREAD

**Issue by ranjitpatel** [KiBa1215/BottomNavigation#1]
In my project the landing page is BottomNavigation
 Screen and i need a default tab to be selected so the content will display of that respective screen, please suggest how can i achieve this .

**Comment by KiBa1215** [comment]
@ranjitpatel Thank you for your issue. I never thought there would be anyone cares about this project...
And for your question, I think you can use```bottomNavigationView.setTab(int position)``` when Acitivity onCreated.
BTW, as Google has supported the library called “BottomNavigationView”, you can simply replace this project with that. 

Thank you again.
